[control_plane]
k3s-master ansible_host=100.48.62.165 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/adeola-key.pem

[workers]
k3s-worker1 ansible_host=100.28.129.144 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/adeola-key.pem
k3s-worker2 ansible_host=98.92.244.107 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/adeola-key.pem

[cluster:children]
control_plane
workers
