- name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./taskapp                # Change this to the folder where requirements.txt actually lives!
          file: ./manifests/Dockerfile      # Keep pointing to your Dockerfile here
          push: true
          tags: ghcr.io/ts-a-devops/taskapp-backend:v1.0.0
