- name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .                # Keep context as the root so it can see all your code
          file: ./manifests/Dockerfile   # Tell it the Dockerfile is in the manifests folder
          push: true
          tags: ghcr.io/ts-a-devops/taskapp-backend:v1.0.0
